services:
  # Service web pour l'API
  - type: web
    name: fifa-predictor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_CREDENTIALS
        sync: false # Vous devrez ajouter ce secret dans l'interface Render

  # Service worker pour le bot Telegram
  - type: worker
    name: fifa-predictor-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python fifa_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_CREDENTIALS
        sync: false # Vous devrez ajouter ce secret dans l'interface Render

  # Service statique pour l'interface web
  - type: static
    name: fifa-predictor-ui
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
