services:
  # Service web pour l'API
  - type: web
    name: fifa-predictor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 5000
      - key: TELEGRAM_TOKEN
        sync: false # Vous ajouterez cette valeur dans l'interface Render
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false # Vous ajouterez cette valeur dans l'interface Render
      - key: SPREADSHEET_ID
        sync: false # Vous ajouterez cette valeur dans l'interface Render
      - key: DEBUG
        value: "False"

  # Service worker pour le bot Telegram
  - type: worker
    name: fifa-predictor-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python fifa_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TELEGRAM_TOKEN
        sync: false # Synchronisé avec le service API
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false # Synchronisé avec le service API
      - key: SPREADSHEET_ID
        sync: false # Synchronisé avec le service API

  # Service statique pour l'interface web
  - type: static
    name: fifa-predictor-ui
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: API_URL
        fromService:
          name: fifa-predictor-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL
